--- #YAML:1.0
name:               Statistics-MVA-BayesianDiscrimination
version:            0.0.2
abstract:           Two-Sample Linear Discrimination Analysis with Posterior Probability Calculation.
author:
    - Daniel S. T. Hughes <dsth@cantab.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:               1.08
    List::Util:         1.19
    Math::Cephes:       0.47
    Statistics::MVA:    0.0.1
    Test::More:         0
    Text::SimpleTable:  2.0
    version:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
